### ISSUE TITLE
Add numRetweets on leaderboard, implement sorting by it or by exposure score

### ISSUE THREAD

**Issue by daisygokhale** [CSE512-15S/fp-ramag-grbritz-kollerz-caandrew#33]

**Comment by zenokoller** [comment]
http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html
or 
http://drvic10k.github.io/bootstrap-sortable/

**Comment by zenokoller** [comment]
I sort of figured it out. Assigned it to me
